### ISSUE TITLE
Index EmailTemplate.Code Changed to unique(code)

### ISSUE THREAD

**Issue by dleinbach** [lekoala/silverstripe-mandrill#15]
This update never goes away when i run the dev/build/?flush-all its always there. Does this mean there is an error somewhere?

**Comment by lekoala** [comment]
well it seems that silverstripe doesn't always detect properly the original value (I have this as well for enum values for instance). Not sure there is anything wrong but I find this annoying as well.

Anyway I removed the unique constraint in the current master because I want the email template to be editable in each subsite, so it won't bother you again :-)

**Comment by dleinbach** [comment]
can you tell me the file that was changed?

**Comment by dleinbach** [comment]
NM found it thanks!
