### ISSUE TITLE
Using package manager

### ISSUE THREAD

**Issue by spekulatius** [lekoala/silverstripe-mandrill#26]
Hello @lekoala 

do you think it would be possible to use the library for mandrill as a composer dependency instead of commiting the library to the git repo here?

This should be the right one https://bitbucket.org/mailchimp/mandrill-api-php shouldn't it be?

Cheers,
Spek

**Comment by lekoala** [comment]
I didn't because it have made two modifications : one to support server without a CA file properly set and another one to handle curl redirect if disabled.
Also, I added documentation to make the sdk more friendly to use.

However, what I can do is to use the sdk in the vendor directory if used and keep the one included as fallback (and exclude the thirdparty dir from the manifest)
